services:
  postgresql:
    container_name: ms_postgres
    image: postgres
    environment:
      - POSTGRES_USER= myuser
      - POSTGRES_PASSWORD= 1234
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=school
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: myuser@email.com
      PGADMIN_DEFAULT_PASSWORD: myuser
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:

volumes:
  postgres:
  pgadmin:
