spring:
  application:
    name: project_management

  sql:
    init:
      schema-locations: classpath:db_init.sql
      mode: always

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/project
    username: myuser
    password: 1234

  datasource:
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
