spring:
  application:
    name: ms_customer

  data:
    mongodb:
      username: myuser
      password: 1234
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090
