spring:
  application:
    name : ms_class
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: myuser
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8087